/*
 * fuzz_parser.c — libFuzzer harness for the golden parser model (Phase 6).
 *
 * Feeds arbitrary fuzzer-generated bytes as a packet through the vertical-slice
 * program (pm_slice_program) and runs the model. Built with libFuzzer +
 * AddressSanitizer + UBSan (nix run .#model-fuzz), so any out-of-bounds packet
 * read, signed-overflow, or other UB the parser could hit on a malformed frame
 * is caught here — the model is the architectural source of truth, so it must be
 * memory-safe on every input, not just the directed corpus.
 *
 * The model must NEVER read outside [pkt, pkt+len): every header access goes
 * through the bounds checks in load_src_off()/read_be(). This fuzzer exists to
 * prove that claim empirically.
 */
#include "parser.h"
#include <stdint.h>
#include <stddef.h>

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /* pm_init takes a uint32_t length; libFuzzer inputs are tiny, but clamp to
     * be safe rather than truncate silently. */
    if (size > 0xFFFFu)
        size = 0xFFFFu;

    size_t nprog;
    const instr *prog = pm_slice_program(&nprog);

    pstate ps;
    struct flow_keys fk;
    pm_init(&ps, data, (uint32_t)size, &fk);
    (void)pm_run(&ps, prog, nprog);

    /* return value is ignored by libFuzzer; the interesting signal is a
     * sanitizer trap (crash) on a bad memory access, not the parser's code. */
    return 0;
}
