# scripts/fpga-vivado-license-check.sh
#
# Phase-A verify-before-buy: what does the installed Vivado license actually PERMIT on the
# target part? The 2026.1 tiered model gates *implementation* per device, so "synth works"
# does not imply "impl+bitstream works". This runs a trivial design (generated by the tcl)
# through synth -> place -> route -> write_bitstream on $XILINX_PART and reports which
# license features Vivado granted and whether a bitstream was produced — with NO board and
# NO CVA6, so a user can confirm their tier before committing to a build (or a purchase).
#
# RESULT on hp5 (2026-09-20, free "Basic" tier, xc7k325tffg900-2): Vivado_Synthesis AND
# Vivado_Implementation both granted; write_bitstream completed. So the full routed-bitstream
# flow is free-tier on the 325T — no edu license needed.
#
# Host-tool dependency (documented impurity, like the other Vivado targets): Vivado is not in
# nixpkgs. Put `vivado` on PATH (source settings64.sh) or export VIVADO=/path/to/bin/vivado;
# on NixOS use the FHS sandbox (nix run .#vivado-fhs). Also export, as needed:
#   VIVADO_SETTINGS         sourced inside the FHS sandbox to put vivado on PATH
#   XILINXD_LICENSE_FILE    path to the node-locked Xilinx.lic (or ~/.Xilinx/Xilinx.lic)
#
# Env knobs:
#   XILINX_PART   part to probe (default xc7k325tffg900-2 — the AX7325B / Genesys 2 die)
#   VIVADO        path to the vivado executable (else `vivado` on PATH)
#
# NOTE for isolcpus hosts: pin to spare cores, e.g. taskset -c 2-7 nix run .#fpga-vivado-license-check
#
# Injected by the Nix wrapper: REPO_ROOT (common.sh).
set -euo pipefail

: "${REPO_ROOT:?REPO_ROOT not set — the Nix wrapper injects it via common.sh}"

PART="${XILINX_PART:-xc7k325tffg900-2}"
VIVADO="${VIVADO:-vivado}"
OUT_DIR="${FPGA_VIVADO_LICCHECK_OUT:-$REPO_ROOT/build/fpga-vivado-license-check}"
TCL="$REPO_ROOT/fpga/vivado/license-probe.tcl"
LOG="$OUT_DIR/license-probe.log"

mkdir -p "$OUT_DIR"

require_vivado() {
  if command -v "$VIVADO" >/dev/null 2>&1; then return 0; fi
  echo "ERROR: vivado not found (looked for '$VIVADO')" >&2
  echo "  install free Vivado (2026.1 'Basic' tier covers all 7-series incl. xc7k325t)," >&2
  echo "  generate its (free) node-locked license, then either:" >&2
  echo "    source /path/to/Xilinx/<ver>/Vivado/settings64.sh   # puts vivado on PATH" >&2
  echo "    export VIVADO=/path/to/Xilinx/<ver>/Vivado/bin/vivado" >&2
  echo "  on NixOS, use the FHS sandbox:" >&2
  echo "    nix run .#vivado-fhs                     # interactive: run the installer here" >&2
  echo "    export VIVADO_SETTINGS=/path/to/Xilinx/<ver>/Vivado/settings64.sh" >&2
  echo "    export VIVADO=\"\$(nix build --no-link --print-out-paths .#vivado-fhs-vivado)/bin/vivado\"" >&2
  exit 1
}

require_vivado

echo "=== Vivado license-boundary probe on $PART ==="
echo "    vivado: $(command -v "$VIVADO")"
echo "    out:    $OUT_DIR"
echo "    (trivial design -> synth -> place -> route -> write_bitstream)"

# Run the probe; capture the full log. Do not abort on a non-zero exit — a license denial
# is itself the answer we want to report (parsed from the log below).
( cd "$OUT_DIR" && "$VIVADO" -mode batch -nojournal -nolog -source "$TCL" -tclargs "$PART" "$OUT_DIR" ) >"$LOG" 2>&1 || true

# ---- parse + VERDICT ------------------------------------------------------------------
grantf() { grep -qiE "Got license for feature '$1'" "$LOG"; }
mark()   { grep -qE "^$1$" "$LOG"; }

LIC_LINE="$(grep -iE "valid Vivado Design Suite .* license has been detected|A valid .* license" "$LOG" | head -1 | sed 's/^[^]]*] //')"

synth_ok=no; impl_lic=no; place_ok=no; route_ok=no; bit_ok=no
grantf "Vivado_Synthesis"      && synth_lic=yes || synth_lic=no
mark   "PROBE_SYNTH_OK"        && synth_ok=yes
grantf "Vivado_Implementation" && impl_lic=yes
mark   "PROBE_PLACE_OK"        && place_ok=yes
mark   "PROBE_ROUTE_OK"        && route_ok=yes
mark   "PROBE_BITSTREAM_OK"    && bit_ok=yes

echo
echo "-------- Vivado license verdict ($PART) --------"
[ -n "$LIC_LINE" ] && echo "  license:        $LIC_LINE"
echo "  synth license:  feature Vivado_Synthesis granted = $synth_lic"
echo "  synth ran:      $synth_ok"
echo "  impl license:   feature Vivado_Implementation granted = $impl_lic"
echo "  place ran:      $place_ok"
echo "  route ran:      $route_ok"
echo "  bitstream:      $bit_ok"
if [ -s "$OUT_DIR/probe.bit" ]; then
  echo "  probe.bit:      $(du -h "$OUT_DIR/probe.bit" | cut -f1) written"
fi
echo "------------------------------------------------"

if [ "$bit_ok" = yes ]; then
  echo "VERDICT: FULL flow (synth + impl + bitstream) is licensed on $PART."
  echo "         Tier-3 pre-buy proof (routed bitstream + timing) is available with this license."
  exit 0
elif [ "$synth_ok" = yes ]; then
  echo "VERDICT: SYNTH is licensed on $PART, but impl/bitstream did NOT complete." >&2
  echo "         Check the log for a license denial vs a design/pin error:" >&2
  echo "           $LOG" >&2
  echo "         If it is a license gate, an edu/university license lifts it for the 325T." >&2
  exit 3
else
  echo "VERDICT: could not complete even synthesis — see the log:" >&2
  echo "           $LOG" >&2
  exit 3
fi
